CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    gendate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expired INTEGER DEFAULT 0
);