provider:
  name: openfaas
  [cite_start]gateway: http://127.0.0.1:8080 # À adapter selon l'IP de votre cluster [cite: 136]

functions:
  generate-password:
    lang: python3-http
    handler: ./functions/generate-password
    [cite_start]image: <votre-pseudo-dockerhub>/cofrap-generate-password:latest [cite: 53]
    environment:
      write_debug: true
      # On ne met jamais les mots de passe ici en clair ! 
    secrets:
      - [cite_start]db-details        # Contient host, user, password de la DB 
      - [cite_start]encryption-key    # La clé Fernet pour le chiffrement [cite: 70]